baseURL = 'https://vietnamese.ocmoxa.com/'
languageCode = 'en-us'
theme = 'etch'
title = 'Vietnamese jottings'

[params]
  description = "Free Vietnamese language grammar notes for beginners"
  copyright = "Copyright © 2022 github.com/hedhyw"
  dark = "auto"
  highlight = true
